MATRICES

In [ ]:
import numpy as np

In [ ]:
np.random.randint(1,21, size=15)

array([20, 13,  6,  7, 20, 20, 11,  1, 10, 18, 20,  9,  7, 17, 19])

In [ ]:
L = [i for i in np.random.randint(1,21, size=40) if i%2==0]
L

[8, 6, 6, 10, 10, 6, 2, 14, 18, 20, 2, 8, 14, 12, 6, 18, 16, 2, 16]

In [15]:
L.pop()#muestra el mas grande

16

In [18]:
L.remove(20)

In [19]:
L + [4]

[8, 6, 6, 10, 10, 6, 2, 14, 18, 2, 8, 14, 12, 6, 18, 16, 2, 4]

In [20]:
L

[8, 6, 6, 10, 10, 6, 2, 14, 18, 2, 8, 14, 12, 6, 18, 16, 2]

In [21]:
L.pop(3)

10

In [22]:
L_arreglo = np.array(L)
L_arreglo

array([ 8,  6,  6, 10,  6,  2, 14, 18,  2,  8, 14, 12,  6, 18, 16,  2])

In [43]:
len(L_arreglo)

16

In [56]:
L_matriz= L_arreglo.reshape(4,4)
L_matriz

array([[ 8,  6,  6, 10],
       [ 6,  2, 14, 18],
       [ 2,  8, 14, 12],
       [ 6, 18, 16,  2]])

In [29]:
L_arreglo.reshape(8,2)

array([[ 8,  6],
       [ 6, 10],
       [ 6,  2],
       [14, 18],
       [ 2,  8],
       [14, 12],
       [ 6, 18],
       [16,  2]])

In [59]:
M_matriz= np.array([2,3,14,19,13,0,25,6,9,1,2,3,4,5,6,7]).reshape(4,4)
M_matriz

array([[ 2,  3, 14, 19],
       [13,  0, 25,  6],
       [ 9,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [60]:
N = L_matriz @ M_matriz
N

array([[188,  80, 334, 276],
       [236, 122, 270, 294],
       [282,  80, 328, 212],
       [398,  44, 578, 284]])